### ISSUE TITLE
Supporting v0.1.1 and upcoming releases

### ISSUE THREAD

**Issue by lissyx** [Elleo/gst-deepspeech#1]
It's great that there is a G-Streamer plugin, however it seems to target v0.1.0. We did a lot of changes now, v0.1.1 is available and current master branch has also a lot of new shining.

Do you have any plan on pushing updates? How can we be of help?

**Comment by Elleo** [comment]
Thanks,

I've now tested with 0.1.1 and the current code is compatible with both 0.1.0 and 0.1.1, I've also updated the PPA to include packages for 0.1.1 and updated gst-deepspeech's packaging.

I'm anticipating making some fairly large changes once streaming support is added (IIRC that's on the roadmap for 0.2?), so if you were able to give me a heads up when that lands in master it'd be greatly appreciated :)

Thanks,
Mike
