### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by djfd** [Elleo/gst-deepspeech#14]
Hi,

I am getting error trying to compile the plugin:
```
In file included from gstdeepspeech.cc:66:
gstdeepspeech.h:67:17: error: ‘DeepSpeech’ is not a namespace-name
 using namespace DeepSpeech;
                 ^~~~~~~~~~
gstdeepspeech.h:67:27: error: expected namespace-name before ‘;’ token
 using namespace DeepSpeech;
                           ^
gstdeepspeech.h:74:3: error: ‘Model’ does not name a type
   Model            *model;
   ^~~~~
```

looking to the [code](https://github.com/Elleo/gst-deepspeech/blob/master/src/gstdeepspeech.h#L67) I cannot see any mentioned workspace definition, it is starting right from the
```cpp
using namespace DeepSpeech;
```
How it is expected to work at all, if we do not have workspace definition? Could you advise please?

Environment: ```Arch linux, x64, up to date```
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC) 
```
DeepSpeech is installed with pip3, headers and libraries set via ```CPP_FLAGS``` and ```LD_LIBRARY_PATH``` respectively

Thanks

**Comment by Elleo** [comment]
Hi djfd,

gst-deepspeech is currently only compatible with DeepSpeech 0.1 and 0.1.1 (latest release version), I suspect you're using a later version as it looks like the namespace has been removed in master. I will be updating gst-deepspeech to work with newer releases of DeepSpeech but only once they're fully released along with compatible model files.

Hope that helps,
Mike

**Comment by Elleo** [comment]
Yep, I agree the documentation could definitely do with expanding. I'm a bit short on free time at the moment, so it might be a while before I have a chance to do anything, however if you're able to collate some questions and answers from the comments on my blog a PR would be very gratefully accepted :)
