### ISSUE TITLE
Upgrade to Coqui STT

### ISSUE THREAD

**Issue by JRMeyer** [Elleo/gst-deepspeech#19]
Hi there 👋

`gst-deepspeech` is an excellent project... thank you for sharing it with the open source community 💚 

You might not know, but [Coqui STT](https://github.com/coqui-ai/stt) is the new, actively maintained fork of DeepSpeech. It would be a fairly easy upgrade, and the new Coqui v1.0 model is **much** more accurate than the previous DeepSpeech v0.9 model 😄

For more context: https://github.com/mozilla/DeepSpeech/issues/3693

**Comment by Elleo** [comment]
Hi!

Thanks for bringing this up, @philn is actually already working on a Coqui based rewrite, that I believe he eventually intends to upstream into the official GStreamer plugins package, so I'm not planning any further work on this branch.

Cheers,
 Mike

**Comment by philn** [comment]
Oops, almost forgot about this... :) Yeah I started a coqui-stt plugin based on this work, but it's not yet ready for a merge request. Anyway, if you want to give it a try, I've pushed my branch there: https://gitlab.freedesktop.org/philn/gstreamer/-/commits/coqui-stt

**Comment by JRMeyer** [comment]
@philn -- any support you need we might be able to help with? You might find our gitter room useful: gitter.im/coqui-ai/stt

the API hasn't changed, so it should be a pretty drag-and-drop change :)

**Comment by philn** [comment]
I haven't found the time to get back to this yet sadly, very very busy 2022 so far :(

**Comment by JRMeyer** [comment]
no pressure:) lmk how we might help 💚
