### ISSUE TITLE
deepspeech.h is missing when building it

### ISSUE THREAD

**Issue by KamelNice06** [Elleo/gst-deepspeech#23]
I try to build the package in my buildroot environment and I m getting this issue :
gstdeepspeech.cc:63:10: fatal error: deepspeech.h: No such file or directory
   63 | #include <deepspeech.h>
      |          ^~~~~~~~~~~~~~

Indeed the file does not seem to be part of the repo

**Comment by Elleo** [comment]
That's correct, that's referring to the deepspeech header file from deepspeech itself, which you'll need to have installed: https://github.com/mozilla/DeepSpeech

However please note that both this repository and deepspeech are deprecated, and that you'd be better off looking at coqui stt and the corresponding branch linked in the repo description.

**Comment by KamelNice06** [comment]
Thx
